name: Fly.io Deployment

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Flyctl Setup
        uses: superfly/flyctl-actions@v1
        with:
          flyctl_version: "0.0.0"
          flyctl_token: ${{ secrets.FLY_API_TOKEN }}
      - name: Deploy to Fly
        run: flyctl deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
